import JSZip from "jszip";
import type { DefineValue, DefinesData, Project } from "../types/defines";

function valueToScript(value: DefineValue): string {
  if (typeof value === "boolean") {
    return value ? "yes" : "no";
  }

  if (typeof value === "number") {
    return Number.isInteger(value) ? `${value}` : `${value}`;
  }

  if (Array.isArray(value)) {
    const values = value.map((item) => {
      if (typeof item === "boolean") {
        return item ? "yes" : "no";
      }

      if (typeof item === "number") {
        return `${item}`;
      }

      return /^@/.test(item) || /^\@\[/.test(item) ? item : item.includes(" ") ? `"${item}"` : item;
    });

    return `{ ${values.join(" ")} }`;
  }

  if (/^@/.test(value) || /^\@\[/.test(value)) {
    return value;
  }

  return `"${value.replaceAll('"', '\\"')}"`;
}

function buildDefinesFile(defines: DefinesData, delta: Record<string, DefineValue>): string {
  const sections: string[] = [];

  for (const category of defines.categories) {
    sections.push(`${category.name} = {`);

    for (const define of category.defines) {
      const value = delta[define.id] ?? define.defaultValue;
      const comment = define.comment ? ` # ${define.comment}` : "";
      sections.push(`  ${define.key} = ${valueToScript(value)}${comment}`);
    }

    sections.push("}", "");
  }

  return sections.join("\n").trimEnd() + "\n";
}

export async function exportProjectZip(project: Project, defines: DefinesData): Promise<Blob> {
  const zip = new JSZip();
  const safeName = project.modName.trim().replace(/[^A-Za-z0-9_-]+/g, "_") || "euv-defines-mod";
  const root = zip.folder(safeName);

  if (!root) {
    throw new Error("Unable to create ZIP root folder.");
  }

  const descriptor = [
    `name=\"${project.modName}\"`,
    `version=\"${project.modVersion}\"`,
    `supported_version=\"${defines.version}\"`,
    `path=\"mod/${safeName}\"`,
    `tags={ \"Gameplay\" }`
  ].join("\n");

  const fullDefines = buildDefinesFile(defines, project.delta);

  zip.file(`${safeName}.mod`, descriptor);
  root.file("descriptor.mod", descriptor);
  root.file("README.txt", project.modDescription || "Generated by EUV Defines Editor");
  root.file("common/defines/00_euv_generated_defines.txt", fullDefines);

  return zip.generateAsync({ type: "blob" });
}
